### PR TITLE
Support universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by SimonSapin** [comment]
What does this do? Isn’t it the default, since there are no C extensions?

**Comment by graingert** [comment]
This isn't the default, but it unlocks the universal wheel for python 2 and 3

**Comment by SimonSapin** [comment]
What does universal wheel mean? What is the default? If I run `bdist_wheel` on Python 2.7.10, is that wheel for 2.7.10 only? For 2.7.x? For 2.x.y? What is the advantage of wheels over source dists, for pure-Python libraries?

Feel free to point me at some documentation rather than re-explain it all here.

**Comment by graingert** [comment]
It means people don't have to build the package twice, once for Python 2
and once for Python 3. It's also slightly more trustworthy because there's
no executable install stage

**Comment by SimonSapin** [comment]
But there’s nothing to build here, is there?

**Comment by SimonSapin** [comment]
To clarify: this PR seems harmless and I don’t mind taking it, I’d just like to understand why it’s useful.

**Comment by graingert** [comment]
But pip doesn't know that

**Comment by SimonSapin** [comment]
Yeah, pip still like to run `bdist_wheel` for its cache. But since there is no C code to build, `bdist_wheel` only copies a few small `.py` files, which should be very fast.

**Comment by graingert** [comment]
That's true: it only shaves a few seconds of the install time:

Eg this builds twice:

```bash
(cssselect2)graingert@galumph:~$ pip install cssselect
Collecting cssselect
  Downloading cssselect-0.9.1.tar.gz
Building wheels for collected packages: cssselect
  Running setup.py bdist_wheel for cssselect
  Stored in directory: /home/graingert/.cache/pip/wheels/c6/0e/79/ae69bf7b31029e0f0bc5b8306547f94ec3926b7dbb8452b5ea
Successfully built cssselect
Installing collected packages: cssselect
Successfully installed cssselect-0.9.1
(cssselect2)graingert@galumph:~$ workon cssselect3
(cssselect3) graingert@galumph:~$ pip install cssselect
Collecting cssselect
  Using cached cssselect-0.9.1.tar.gz
Building wheels for collected packages: cssselect
  Running setup.py bdist_wheel for cssselect
  Stored in directory: /home/graingert/.cache/pip/wheels/c6/0e/79/ae69bf7b31029e0f0bc5b8306547f94ec3926b7dbb8452b5ea
Successfully built cssselect
Installing collected packages: cssselect
Successfully installed cssselect-0.9.1
```
I've pasted the relevant parts from the [Python Wheels list of advantages](http://pythonwheels.com/#advantages):
>    Faster installation for pure python ...
>    Avoids arbitrary code execution for installation. (Avoids setup.py)
>    ...
>    Allows better caching for testing and continuous integration.
>    Creates .pyc files as part of installation to ensure they match the python interpreter used.
>    More consistent installs across platforms and machines.

**Comment by SimonSapin** [comment]
>  Creates .pyc files as part of installation to ensure they match the python interpreter used.

Doesn’t `universal = 1` defeat this?

**Comment by graingert** [comment]
No, it enables it. pyc building happens at install time

**Comment by SimonSapin** [comment]
I’m not super convinced by the upsides, but I don’t see a downside either so let’s merge this.

**Pull request merged**
